# ========================
# 核心配置
# ========================
title: My Knowledge Base
baseurl: "/myblog"
url: "https://zhurongxiao.github.io"
timezone: Asia/Shanghai
lang: zh-CN
encoding: utf-8

# ========================
# Jekyll设置
# ========================
markdown: kramdown
highlighter: rouge
future: true
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle

# ========================
# 插件配置 (GitHub Pages官方支持)
# ========================
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-paginate

# ========================
# 集合配置
# ========================
collections:
  posts:
    output: true
    permalink: /:categories/:title/
  search:
    output: true
    permalink: /search/

# ========================
# 分类配置
# ========================
custom_categories:
  - name: Rust
    path: /rust/
    icon: fa-brands fa-rust
  - name: Shell
    path: /shell/
    icon: fas fa-terminal
  - name: Mac
    path: /mac/
    icon: fab fa-apple
  - name: Gather
    path: /gather/
    icon: fa-solid fa-toolbox
  - name: Life
    path: /life/
    icon: fa-solid fa-heart-pulse
  - name: Mixed
    path: /mixed/
    icon: fa-solid fa-pencil
# ========================
# 默认值
# ========================
defaults:
  - scope:
      type: posts
      categories: rust
    values:
      rust_version: "1.70.0"

# ========================
# 技术优化
# ========================
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    block:
      line_numbers: false

sass:
  style: compressed
  sourcemap: never
